"""init users - add avatar, public_id columns

Revision ID: 5c675bb9f48e
Revises: c2403013181b
Create Date: 2025-09-14 19:29:45.314031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c675bb9f48e'
down_revision: Union[str, None] = 'c2403013181b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('public_id', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_id')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
